### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by goneri**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1471
Copy of https://github.com/ansible-community/ansible.plugin_builder/pull/5

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
@GomathiselviS the tests fail with this error:

```
2022-03-10 20:33:27.097591 | LOOP [Set SSH interface IP for IOSXR]
2022-03-10 20:33:37.834684 | controller | ERROR
2022-03-10 20:33:37.835002 | controller | {
2022-03-10 20:33:37.835045 | controller |   "msg": "The conditional check 'hostvars[item].ansible_network_os in ['iosxr']' failed. The error was: error while evaluating conditional (hostvars[item].ansible_network_os in ['iosxr']): 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_network_os'\n\nThe error appears to be in '/var/lib/zuul/builds/eac7333cffd34bc3a1573216e24bbc53/untrusted/project_0/github.com/ansible/ansible-zuul-jobs/playbooks/ansible-network-appliance-base/pre.yaml': line 19, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Set SSH interface IP for IOSXR\n      ^ here\n"
2022-03-10 20:33:37.835077 | controller | }

```

**Comment by NilashishC** [comment]
@goneri That is strange. The tests just needs localhost to run. Not sure why IOS-XR is being pulled in.

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Pull request closed without merging**
